stages:
  integration:
    cmd: python -m jupyter nbconvert --to notebook --execute src/data/integration.ipynb
    deps:
      - src/data/integration.ipynb
      - data/raw
    # не будет работать код ниже
    # не хочу отслеживать data/interim и data/processed
    # но если они в .dvcignore, то и dvc.yaml они использоваться не будут
    # минусы: запускать с флажком -f после появления dvc.lock
    # outs:
    #   - data/interim:
    #       cache: false

  processing:
    cmd: python -m jupyter nbconvert --to notebook --execute src/data/process.ipynb
    deps:
      - src/data/process.ipynb
      # нужно, чтобы он существовал до dvc repro. Костыли, но пока так
      - data/interim

  train:
    cmd: python -m src.model.train
    deps:
      - src/data/dataset.py
      - src/model/gru.py
      - src/model/train.py
      - data/processed