stages:
  integration:
    cmd: python -m jupyter nbconvert --to notebook --execute src/data/integration.ipynb
    deps:
      - src/data/integration.ipynb
      - data/raw/ERA5-Land-Moisture
      - data/raw/USDA
      - data/raw/WRF-HRRR
    # не будет работать код ниже
    # не хочу отслеживать data/interim и data/processed
    # но если они в .dvcignore, то и dvc.yaml они использоваться не будут
    # минусы: запускать с флажком -f после появления dvc.lock
    # outs:
    #   - data/interim:
    #       cache: false

  processing:
    cmd: python -m jupyter nbconvert --to notebook --execute src/data/process.ipynb
    deps:
      - src/data/process.ipynb
      # нужно, чтобы он существовал до dvc repro. Костыли, но пока так
      - data/interim