version: "3"
services: 
  app:
    build: ./app/
    image: crop-predictor-api:latest 
    container_name: crop-predictor-api
    restart: unless-stopped
    env_file:
    - ./app/.env
    volumes:
      - ./app:/app
      - files:/app/files
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - crop-predictor-network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
  ml_worker:
    build: ./ml_worker/
    image: crop-predictor-ml-worker:latest
    container_name: crop-predictor-ml-worker
    restart: unless-stopped
    runtime: nvidia
    volumes:
      - ./ml_worker:/app
      - files:/app/files
      - ../models/:/app/models/
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - crop-predictor-network
  web:
    image: nginx:alpine3.21
    container_name: crop-predictor-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - crop-predictor-network
  db:
    image: postgres:16-alpine
    container_name: crop-predictor-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - crop-predictor-network
  rabbitmq:
    image: rabbitmq:3.13.1-management-alpine
    container_name: crop-predictor-rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "15672:15672"  # Management UI
      - "5672:5672"    # AMQP protocol
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 20s
      timeout: 10s
      retries: 3
    networks:
      - crop-predictor-network

volumes:
  postgres_data:
  rabbitmq_data:
  files:

networks:
  crop-predictor-network:
    name: crop-predictor-network
    driver: bridge
